### ISSUE TITLE
errors in COFs

### ISSUE THREAD

**Issue by SimonEnsemble** [danieleongari/CURATED-COFs#35] opened 2022-07-29 22:19 UTC
overlapping atoms in:
```julia
xtals_w_overlap = ["20010N2", "21131N2"]
```

<img width="308" alt="image" src="https://user-images.githubusercontent.com/30643894/181852017-ce7fab4c-5419-4bc1-98e1-44190c4a17c9.png">

**Comment by mpougin** [comment] 2022-07-31 10:15
hello @SimonEnsemble, 
thank you for spotting this. 
@danieleongari, how do you handle these? Cleaning them manually?

**Comment by danieleongari** [comment] 2022-08-01 07:15
Thanks @SimonEnsemble for the prompt notice.

@mpougin, first it would be nice to understand why our hooks on the commits did not spot this.
Second, I would suggest to take the usual pragmatic approach: if it takes more than 15-30 minutes to fix each of them and they are not coming from a very-high impact journal, you can move them to the list of "discarded" CIFs and that's it.
Thanks for handling this!

**Comment by mpougin** [comment] 2022-08-01 12:09
thanks for your feedback @danieleongari. I will come back to it by middle/end of the week

**Comment by SimonEnsemble** [comment] 2022-08-02 15:45
our `Xtals.jl` code detects overlap automatically; this is how we found the error. when we try to load in the `.cif`, it fails.

CC @eahenle 

```julia
using Xtals
xtal = Crystal("cif_name.cif", check_overlap=true) # well, check_overlap is by default true.
```

**Comment by eahenle** [comment] 2022-08-02 21:00
There is also an "overlap" between atoms in 21192N2.cif, because of periodic boundary conditions--there are two images of the structure, each of which lies in a parallel boundary plane of the unit cell (making them actually coincident).

Inspecting the structure shows another artifact: "orphan" hydrogens hanging out in the middle of empty space.
![image](https://user-images.githubusercontent.com/16201240/182472286-531cab5b-1ffd-4725-ad40-f4e711634257.png)

There are 64 additional structures that raise warnings on calling `Xtals.infer_bonds!`, which may indicate this kind of lone-atom artifact occurs elsewhere.  I will look into this and report back if I find additional issues.

**Comment by eahenle** [comment] 2022-08-03 00:53
There are a few problems in the structures I reviewed.  See my PR for details.  Happy to help you reproduce the workflow, or possibly incorporate an `Xtals.jl` workflow into your CI to help detect these kinds of things in the future.

**Comment by eahenle** [comment] 2022-08-08 15:53
I think @mpougin and I have sorted this all out.  Once #36 is merged, this issue can close.

**Comment by mpougin** [comment] 2022-08-10 15:19
Thank you for your valuable input @SimonEnsemble and @eahenle, I close this now

**Closed as completed by mpougin** 2022-08-10 15:19 UTC
